export const verbs = [
    'vaknar',
    'regnar',
    'gnistrar',
    'palla',
    'prata',
    'vinna',
    'förlora',
    'beräkna',
    'återta',
    'erövra',
    'fundera',
    'hitta',
    'leta',
    'sakna',
    'frita',
    'flörta',
    'hoppas',
    'orkar',
    'sminka',
    'svika',
    'tänka',
    'ana',
    'misstänka',
    'stänka',
    'kasta',
    'grumla',
    'bita',
    'misstro',
    'löpa',
    'kantra',
    'klättra',
    'fajtas',
    'micra',
    'slappa',
    'ligga på latsidan',
    'öva',
    'basta',
    'koppla',
    'husera',
    'flytta',
    'levla',
    'snacka slang',
    'snacka skit',
    'ljuga',
    'dricka',
    'konstra',
    'måla in sig i ett hörn',
    'vandra',
    'skada sig',
    'åka',
    'härma',
    'fåna sig',
    'åma sig',
    'låta bli',
    'sluta',
    'börja',
    'skriva på',
    'anteckna',
    'läsa',
    'mysa',
    'avslöja',
    'fresta',
    'baka',
    'laga mat',
    'plugga',
    'bygga',
    'spatsera',
    'barnvakta',
    'värva',
    'predika',
    'motstå',
    'leka',
    'knappra',
    'knapra',
    'glufsa',
    'smitta',
    'döda',
    'misshandla',
    'trumpeta',
    'blåsa',
    'åka skidor',
    'köra bil',
    'massera',
    'duplicera',
    'fuska',
    'kopiera',
    'åstadkomma',
    'rita',
    'låna',
    'shoppa',
    'minska',
    'öka',
    'tråka',
    'bli',
    'lida',
    'njuta',
    'kasta sig ut',
    'äventyra',
    'smyga',
    'klampa',
    'dundra',
    'förstå',
    'likställa',
    'jämföra',
    'insupa',
    'må',
    'räcka ut en hand',
    'uppoffra',
    'spara',
    'titta på klockan',
    'titta på tv',
    'slå sönder',
    'laga',
    'plåstra',
    'påstå',
    'insistera',
    'skärpa sig',
    'snöa',
    'klaga',
    'ansöka',
    'stapla',
    'fiska',
    'virka',
    'älta'
];