export const whenOrWhere = [
    'när alla andra somnat',
    'innan solen går upp',
    'i matsalen',
    'innan han ser oss',
    'medan hon fortfarande bryr sig',
    'innan allt tar slut',
    'i det öde huset',
    'i duschen',
    'på bokrean',
    'på Ica Maxi',
    'samtidigt',
    'under tiden',
    'i spöktimmen',
    'under solnedgången',
    'i det blå',
    'på månen',
    'under en bil',
    'i kundvagnen',
    'runt midsommarstången',
    'på semestern',
    'bland raukarna',
    'i ljungen',
    'bland vitsipporna',
    'i parken',
    'när du vill',
    'medan han tänker på annat',
    'när hon lagar mat',
    'på väg till jobbet',
    'på väg till sjukhuset',
    'i taxin',
    'på cykeln',
    'i vintertid',
    'på Gotland',
    'i Stockholm',
    'utomlands',
    'på tågluffen',
    'vid relingen',
    'under däck',
    'uppe i tornet',
    'i källaren',
    'under taknocken'
];