export const whenOrWhere = [
    'när alla andra somnat',
    'innan solen går upp',
    'i matsalen',
    'innan han ser oss',
    'medan hon fortfarande bryr sig',
    'innan allt tar slut',
    'i det öde huset',
    'i duschen',
    'på bokrean',
    'på Ica Maxi',
    'samtidigt',
    'under tiden',
    'i spöktimmen',
    'under solnedgången',
    'i det blå',
    'på månen',
    'under en bil',
    'i kundvagnen',
    'runt midsommarstången',
    'på semestern',
    'bland raukarna',
    'i ljungen',
    'bland vitsipporna',
    'i parken',
    'när du vill',
    'medan han tänker på annat',
    'när hon lagar mat',
    'på väg till jobbet',
    'på väg till sjukhuset',
    'i taxin',
    'på cykeln',
    'i vintertid',
    'på Gotland',
    'i Stockholm',
    'utomlands',
    'på tågluffen',
    'vid relingen',
    'under däck',
    'uppe i tornet',
    'i källaren',
    'under taknocken',
    'i alldeles för många sekunder',
    'med näsan i en bok',
    'i julgranen',
    'runt bordet',
    'på buffébordet',
    'i poolen',
    'i bastun',
    'på stranden',
    'på kontorsfesten',
    'på klassfesten',
    'på skolavslutningen',
    'i skogen',
    'på joggingrundan',
    'i trikåer',
    'på Nordpolen',
    'i en luftballong',
    'i fantasin',
    'medan någon förblöder',
    'när elden falnar',
    'när det skymmer',
    'när glöden är perfekt',
    'när kläderna torkat',
    'i soffan',
    'på AW',
    'i fontänen',
    'på toa',
    'i tvättstugan',
    'på semestern',
    'under granskningen',
    'inför hennes blick',
    'under kniven',
    'på ett näckrosblad',
    'i en rymdraket',
    'i mellanrummet',
    'under soffan',
    'i medvetandet',
    'på dansgolvet',
    'hemma',
    'till havs',
    'om vi kommer undan med det',
    'innan tåget går',
    'innan vi blir gamla',
    'innan du gifter dig',
    'innan det är för sent',
    'medan regnbågen bleknar',
    'när du kommer hem',
    'i storstaden',
    'på landet',
    'där jag aldrig varit förut',
    'i mörkret',
    'när jag vill',
    'vid fruktdisken',
    'i omloppsbana',
    'när insikten sjunker in',
    'i framtiden',
    'på stenåldern',
    'på Gröna Lund',
    'på Nordpolen',
    'på badhuset',
    'på köplats 59',
    'i telefonkö',
    'i terapisoffan',
    'på en öde ö',
    'på syjuntan',
    'på kafferepet'
];